default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV['APP_DB_NAME'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PW'] %>
  port: <%= ENV['APP_DB_PORT'] %>

development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV['APP_DB_NAME'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PW'] %>
  port: <%= ENV['APP_DB_PORT'] %>
  reconnect: false

test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV['APP_DB_NAME'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PW'] %>
  port: <%= ENV['APP_DB_PORT'] %>
  reconnect: false

staging: 
  <<: *default
  reconnect: true
  
production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV['APP_DB_NAME'] %>
  pool: <%= ENV['APP_DB_POOL'] %>
  host: <%= ENV['APP_DB_HOST'] %>
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PW'] %>
  port: <%= ENV['APP_DB_PORT'] %>
  reconnect: false