# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 649b7a7561d7de5b6f8c660311f220e82c7b3ce8d6af20198a7e8710d81aa1f3bbc2099522ea8f27f6a1b7ed5e9adc7a1eda923c61a8d6208ec6178db5d77885

test:
  secret_key_base: d0eb2c68f8ba0ffc605c6c563c841332d3f464e1aa03e9f6cffb568e3bf4b47fc72d2bdce9759fbe91b34745696ca665555079a5285d2bc05317cc38be261cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
